language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
compiler: gcc
install:
- ls -l /usr/local/lib
- python setup.py build_ext -I /usr/local/include/ -L /usr/local/lib/ -R /usr/local/lib/
- python setup.py install
dist: trusty
sudo: required
before_install:
- git clone https://github.com/RRZE-HPC/likwid.git
- cd likwid
- make && sudo make install
- cd ..
before_script:
- sudo modprobe msr
script:
- python -c "import pylikwid"
- "./tests/testtopo.py"
- "./tests//testpin.py"
- "./tests//testaffinity.py"
deploy:
  provider: pypi
  skip_existing: true
  user: travis.rrze-hpc
  password:
    secure: iqXaZAwnR5dnVK9KXgCFiqII3/EpBruluuunXraYnELt11+pxfeea4FbvNi6V8X2EYS+EQWleObuQ4kY9zR5MTG9cYKYJSzO1adkcq6zKIXDFIOz2bKnENhJ35ofCmQa0MyhizzdDB7wk/2oK9Y1ZyLHPk+uWQiAKFgWF05tyaKiN4Fy/PEIJhp/Sz59QTBNtSAo3/vXp8VjLSJ1JHwqBE5xu9K212AP5NEbF9QdsWUufyaEbP/hF5+tDGJXT4XebNCIRG6aMlKW9gJoX6ELZpXueCfJKD5Q2D55B/YT4ceNl5SQGavLEFJWLGLDSuMYMx9cSloSzT/ORjtHOW7PLU/lO45yLdu8ts64SJXO+mlBrZzywqt5aQlgOHGXvvWslmN148HoZyFsbnPOmtOwEvoNMCbuwhYiHcni4Lj7SbrwltF49IJQMjpWwGJaQc1AUA1crdCJgScpZCm/IuQq0XZ26SNlFHYfMAUaUB4sSdZIaaELEzPv+d1S2NEmLcAc41I0vIbt75zStaMTGcZpq8Siq+/p9m7bJvXQ1NverghzOKOUJErdNfnMHHzT72y8G1dUCHEzSGbmHzLUWaoW/0wqd6y7210W+0mSaFOvaNWhsa8aavDFv7ImN6mMKCBoESTTPLCxPbtl43eA0syt8dw+yKssfuR4T32T/d/07bw=
  distributions: sdist
  skip_cleanup: true
  on:
    repo: RRZE-HPC/pylikwid
